"""esquema inicial (regras v2)

Revision ID: 05a044b93121
Revises: 
Create Date: 2026-07-23 22:21:26.663179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Enum 'cor' (regras 2.5/2.6): criado/dropado UMA vez, explicitamente, no Postgres.
# O autogenerate gera duas instâncias de sa.Enum(name='cor') (uma por tabela) e
# cada create_table emitiria CREATE TYPE cor -> o 2º falha com DuplicateObject.
# Correção manual: postgresql.ENUM(create_type=False) — ao contrário de sa.Enum,
# o create_type=False é honrado pelo impl PG (o create_table NÃO emite CREATE TYPE);
# o tipo é criado/dropado uma vez pelos .create()/.drop() explícitos abaixo.
# Em SQLite, postgresql.ENUM renderiza como VARCHAR + CHECK (create_type ignorado).
cor_type = postgresql.ENUM('preta', 'vermelha', name='cor', create_type=False)


# revision identifiers, used by Alembic.
revision: str = '05a044b93121'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        cor_type.create(bind, checkfirst=True)   # cria o tipo 'cor' UMA vez
    op.create_table('circulo_hierarquico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('eh_praca', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('ordem')
    )
    op.create_table('escala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tem_preta', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('tem_vermelha', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('folga_minima_horas', sa.Integer(), nullable=True),
    sa.Column('inicio_servico', sa.Time(), server_default=sa.text("'08:00:00'"), nullable=False),
    sa.Column('duracao_horas', sa.Integer(), server_default=sa.text('(24)'), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('duracao_horas > 0', name='ck_duracao'),
    sa.CheckConstraint('folga_minima_horas IS NULL OR folga_minima_horas >= 24', name='ck_folga_piso'),
    sa.CheckConstraint('tem_preta OR tem_vermelha', name='ck_ao_menos_uma_cor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feriado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nacional', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('organizacao_militar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('sigla', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('override_dia',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cor', cor_type, server_default='vermelha', nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('data')
    )
    op.create_table('tipo_impedimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escala_concorrente',
    sa.Column('escala_menor_id', sa.Integer(), nullable=False),
    sa.Column('escala_maior_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('escala_menor_id < escala_maior_id', name='ck_par_ordenado'),
    sa.ForeignKeyConstraint(['escala_maior_id'], ['escala.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escala_menor_id'], ['escala.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('escala_menor_id', 'escala_maior_id')
    )
    op.create_table('posto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('rotulo', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['escala_id'], ['escala.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escala_id', 'ordem', name='uq_posto_escala_ordem')
    )
    op.create_table('posto_graduacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=12), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem_hierarquica', sa.Integer(), nullable=False),
    sa.Column('circulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circulo_id'], ['circulo_hierarquico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordem_hierarquica'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('militar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_guerra', sa.String(length=60), nullable=False),
    sa.Column('nome_completo', sa.String(length=160), nullable=False),
    sa.Column('identidade', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('posto_graduacao_id', sa.Integer(), nullable=False),
    sa.Column('om_id', sa.Integer(), nullable=False),
    sa.Column('data_promocao', sa.Date(), nullable=False),
    sa.Column('data_praca', sa.Date(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('numero_antiguidade', sa.Integer(), nullable=True),
    sa.Column('ordem_manual', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['om_id'], ['organizacao_militar.id'], ),
    sa.ForeignKeyConstraint(['posto_graduacao_id'], ['posto_graduacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('identidade')
    )
    op.create_table('impedimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('militar_id', sa.Integer(), nullable=False),
    sa.Column('tipo_impedimento_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.CheckConstraint('fim >= inicio', name='ck_periodo'),
    sa.ForeignKeyConstraint(['militar_id'], ['militar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_impedimento_id'], ['tipo_impedimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impedimento', schema=None) as batch_op:
        batch_op.create_index('ix_impedimento_militar', ['militar_id', 'inicio', 'fim'], unique=False)

    op.create_table('participacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('militar_id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['escala_id'], ['escala.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['militar_id'], ['militar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('militar_id', 'escala_id', name='uq_participacao_militar_escala')
    )
    with op.batch_alter_table('participacao', schema=None) as batch_op:
        batch_op.create_index('ix_participacao_escala', ['escala_id'], unique=False, postgresql_where=sa.text('ativo'), sqlite_where=sa.text('ativo'))

    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('posto_id', sa.Integer(), nullable=False),
    sa.Column('militar_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('cor', cor_type, nullable=False),
    sa.Column('inicio_dt', sa.DateTime(), nullable=False),
    sa.Column('termino_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escala_id'], ['escala.id'], ),
    sa.ForeignKeyConstraint(['militar_id'], ['militar.id'], ),
    sa.ForeignKeyConstraint(['posto_id'], ['posto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posto_id', 'dia', name='uq_servico_posto_dia')
    )
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.create_index('ix_servico_escala_dia', ['escala_id', 'dia'], unique=False)
        batch_op.create_index('ix_servico_militar_cor', ['militar_id', 'cor', 'dia'], unique=False)
        batch_op.create_index('ix_servico_termino', ['militar_id', 'termino_dt'], unique=False)

    op.create_table('permuta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('militar_substituto_id', sa.Integer(), nullable=False),
    sa.Column('autorizado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['autorizado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['militar_substituto_id'], ['militar.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permuta')
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_index('ix_servico_termino')
        batch_op.drop_index('ix_servico_militar_cor')
        batch_op.drop_index('ix_servico_escala_dia')

    op.drop_table('servico')
    with op.batch_alter_table('participacao', schema=None) as batch_op:
        batch_op.drop_index('ix_participacao_escala', postgresql_where=sa.text('ativo'), sqlite_where=sa.text('ativo'))

    op.drop_table('participacao')
    with op.batch_alter_table('impedimento', schema=None) as batch_op:
        batch_op.drop_index('ix_impedimento_militar')

    op.drop_table('impedimento')
    op.drop_table('militar')
    op.drop_table('posto_graduacao')
    op.drop_table('posto')
    op.drop_table('escala_concorrente')
    op.drop_table('auditoria')
    op.drop_table('usuario')
    op.drop_table('tipo_impedimento')
    op.drop_table('override_dia')
    op.drop_table('organizacao_militar')
    op.drop_table('feriado')
    op.drop_table('escala')
    op.drop_table('circulo_hierarquico')
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        cor_type.drop(bind, checkfirst=True)     # remove o tipo 'cor' (ver 3.3)
    # ### end Alembic commands ###
